import "./globals.css";
import type { ReactNode } from "react";
import type { Metadata } from "next";
import { PrelineScript } from "@/components/PrelineScript";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <PrelineScript />
        {children}
      </body>
    </html>
  );
}
